# Generated by Django 2.2.1 on 2020-11-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitanteD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_d', models.CharField(max_length=100, verbose_name='Nombre Beneficiario')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('cedula', models.CharField(max_length=100, verbose_name='Cedula Beneficiario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('nombre_banco', models.CharField(choices=[('', 'SELECCIONE BANCO'), ('PACIFICO', 'PACIFICO'), ('BOLIVARIANO', 'BOLIVARIANO')], max_length=100, verbose_name='Nombre del Banco')),
                ('tipo_cuenta', models.CharField(choices=[('AHORRO', 'AHORRO'), ('CORRIENTE', 'CORRIENTE')], default='AHORRO', max_length=100, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(max_length=100, verbose_name='Numero de Cuenta')),
                ('wallet', models.CharField(max_length=100, verbose_name='Numero de Wallet')),
            ],
            options={
                'verbose_name': 'SolicitanteD',
                'verbose_name_plural': 'SolicitanteDs',
            },
        ),
        migrations.CreateModel(
            name='SolicitanteU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_u', models.CharField(max_length=255, verbose_name='Nombres Depositante')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('cedula', models.CharField(max_length=100, verbose_name='Cedula Beneficiario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'SolicitanteU',
                'verbose_name_plural': 'SolicitanteUs',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('', 'SELECCIONE OPERACIÓN'), ('COMPRA', 'COMPRA'), ('VENTA', 'VENTA')], max_length=100, verbose_name='Tipo Operación')),
                ('monto_principal', models.IntegerField(verbose_name='Monto Principal')),
                ('monto_cripto', models.IntegerField(verbose_name='Monto Cripto')),
                ('monto_total', models.IntegerField(verbose_name='Monto Total')),
                ('num_referencia', models.CharField(max_length=100, verbose_name='Numero de Referencia')),
                ('cargar_documento', models.ImageField(upload_to='operaciones/', verbose_name='Cargar Documento')),
                ('estado_procesada', models.BooleanField(default=False, verbose_name='Procesada/No Procesada')),
                ('estado_pendiente', models.BooleanField(default=False, verbose_name='Pendiente/No Pendiente')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_solicigtanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.SolicitanteD')),
                ('id_solicigtanteu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.SolicitanteU')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
            },
        ),
    ]
