# Generated by Django 2.2.1 on 2020-12-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20201201_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datos', models.CharField(choices=[('MISMOS DATOS', 'MISMOS DATOS'), ('OTROS DATOS', 'OTROS DATOS')], max_length=100, verbose_name='Tipo de Datos')),
                ('nombre_ben', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Beneficiario')),
                ('tipo_documento_ben', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Documento')),
                ('cedula_ben', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cedula Beneficiario')),
                ('correo_ben', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('nombre_banco', models.CharField(blank=True, choices=[('', 'SELECCIONE BANCO'), ('PACIFICO', 'PACIFICO'), ('BOLIVARIANO', 'BOLIVARIANO')], max_length=100, null=True, verbose_name='Nombre del Banco')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORRO', 'AHORRO'), ('CORRIENTE', 'CORRIENTE')], default='AHORRO', max_length=100, null=True, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Cuenta')),
                ('wallet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Wallet')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sol', models.CharField(max_length=255, verbose_name='Nombres Solicitante')),
                ('tipo_documento_sol', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('cedula_sol', models.CharField(max_length=100, verbose_name='Cedula Solicitante')),
                ('correo_sol', models.EmailField(max_length=254, verbose_name='Correo Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='id_solicitanted',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='id_solicitanteu',
        ),
        migrations.DeleteModel(
            name='SolicitanteD',
        ),
        migrations.DeleteModel(
            name='SolicitanteU',
        ),
        migrations.AddField(
            model_name='operacion',
            name='id_beneficiario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='example.Beneficiario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacion',
            name='id_solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='example.Solicitante'),
            preserve_default=False,
        ),
    ]
