# Generated by Django 2.2.1 on 2020-12-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20201202_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='tipo_cripto',
            field=models.CharField(choices=[('', 'SELECCIONE CRIPTO'), ('BITCOIN', 'BITCOIN'), ('ETHEREUM', 'ETHEREUM'), ('DASH', 'DASH'), ('RIPLE', 'RIPLE'), ('BAT', 'BAT')], default=1, max_length=100, verbose_name='Tipo Cripto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='datos',
            field=models.CharField(choices=[('MISMOS DATOS', 'MISMOS DATOS'), ('OTROS DATOS', 'OTROS DATOS')], default='MISMOS DATOS', max_length=100, verbose_name='Tipo de Datos'),
        ),
    ]
