# Generated by Django 2.2.1 on 2020-12-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_auto_20201205_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='cedula_ben',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cedula Beneficiario'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='correo_ben',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='datos',
            field=models.CharField(blank=True, choices=[('', 'SELECCIONE DATOS'), ('MISMOS DATOS', 'MISMOS DATOS'), ('OTROS DATOS', 'OTROS DATOS')], default='MISMOS DATOS', max_length=100, verbose_name='Tipo de Datos'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nombre_banco',
            field=models.CharField(blank=True, choices=[('', 'SELECCIONE BANCO'), ('PACIFICO', 'PACIFICO'), ('BOLIVARIANO', 'BOLIVARIANO')], max_length=100, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nombre_ben',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Beneficiario'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de Cuenta'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('AHORRO', 'AHORRO'), ('CORRIENTE', 'CORRIENTE')], default='AHORRO', max_length=100, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_documento_ben',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de Wallet'),
        ),
    ]
