# Generated by Django 2.2.1 on 2020-12-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_auto_20201205_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='datos',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_datos',
            field=models.CharField(blank=True, choices=[('', 'SELECCIONE DATOS'), ('MISMOS DATOS', 'MISMOS DATOS'), ('OTROS DATOS', 'OTROS DATOS')], max_length=100, null=True, verbose_name='Tipo de Datos'),
        ),
    ]
