# Generated by Django 2.2.1 on 2020-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_remove_beneficiario_tipo_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_datos',
            field=models.CharField(blank=True, choices=[('', 'SELECCIONE DATOS'), ('MISMOS DATOS', 'MISMOS DATOS'), ('OTROS DATOS', 'OTROS DATOS')], max_length=100, null=True, verbose_name='Tipo de Datos'),
        ),
    ]
