# Generated by Django 2.2.1 on 2020-12-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_auto_20201205_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='tipo_cripto',
            field=models.CharField(choices=[('', 'SELECCIONE CRIPTO'), ('BITCOIN', 'BITCOIN'), ('ETHEREUM', 'ETHEREUM'), ('DASH', 'DASH'), ('RIPLE', 'RIPLE'), ('BAT', 'BAT')], max_length=100, verbose_name='Tipo Cripto'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('', 'SELECCIONE OPERACIÓN'), ('COMPRA', 'COMPRA'), ('VENTA', 'VENTA')], max_length=100, verbose_name='Tipo Operación'),
        ),
    ]
